#
# Application Name
#
# The name of the application.
#
name: 'TypicalBot'

#
# Application Environment
#
# The environment of the application.
#
environment: 'production'

#
# Application Timezone
#
# The timezone of the application.
#
timezone: 'UTC'

#
# Application Locale
#
# The locale of the application. For a list of supported locales, please
# visit: https://github.com/typicalbot/localization
#
locale: 'en_US'